#!/usr/bin/python

import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from mybottleapp import application

